"""
Phase 6 — Visualization Runner.

Generates all paper-quality figures from pre-computed Phase 4/5 results.
Saves PNGs to results/figures/.

Required pre-computed files (already generated by Phase 4/5):
  checkpoints/gcn_cora_baseline.npz
  results/attacked_graphs/cora_<attack>.npz
  results/defended_graphs/defended_<attack>.npz
"""
import sys
import numpy as np
from pathlib import Path

# ── Project root on sys.path ──────────────────────────────────────────────────
ROOT = Path(__file__).parent
sys.path.insert(0, str(ROOT))

from utils.config import cfg
from datasets.cora_loader import GraphData
from models.gcn import create_gcn
from models.train import predict, load_params
from utils.metrics import classification_metrics

from visualization.bar_charts import plot_accuracy_bar, plot_metrics_grouped
from visualization.line_plots import (
    plot_attack_defense_line,
    plot_training_curves,
)
from visualization.graph_viz import plot_graph_comparison, plot_degree_distribution
from visualization.embeddings import plot_embeddings_comparison


# ── Confirmed Phase 4/5 results (from phase4_attack_results.md) ──────────────
BASELINE_ACC = 0.8010

ATTACKED_ACCS = {
    "nettack":              0.7910,
    "meta_attack":          0.8020,
    "random_structure":     0.7540,
    "feature_perturbation": 0.4190,
    "edge_flip":            0.7360,
    "gradient_attack":      0.0000,
}

DEFENDED_ACCS = {
    "nettack":              0.8040,
    "meta_attack":          0.7950,
    "random_structure":     0.7430,
    "feature_perturbation": 0.7390,
    "edge_flip":            0.7290,
    "gradient_attack":      0.9210,
}

# F1 scores
ATTACKED_F1 = {
    "nettack":              0.7822,
    "meta_attack":          0.7934,
    "random_structure":     0.7473,
    "feature_perturbation": 0.1784,
    "edge_flip":            0.7248,
    "gradient_attack":      0.0000,
}

DEFENDED_F1 = {
    "nettack":              0.7972,
    "meta_attack":          0.7885,
    "random_structure":     0.7370,
    "feature_perturbation": 0.7426,
    "edge_flip":            0.7232,
    "gradient_attack":      0.9123,
}

BASELINE_F1 = 0.7930

FIGURES_DIR = cfg.figures_dir


def load_graph_npz(path: Path, ref_graph: GraphData) -> GraphData:
    """Load a saved graph npz and re-wrap as GraphData."""
    d = np.load(path)
    g = ref_graph.copy()
    g = g.update_adj(d["adj"])
    g = g.update_features(d["features"])
    return g


def load_cora_graph():
    from datasets.cora_loader import load_cora
    print("[Data] Loading Cora …")
    return load_cora(cfg.data_dir)


def load_gcn_and_params(cora):
    import jax
    import jax.numpy as jnp
    from utils.graph_utils import normalize_adjacency

    model = create_gcn(
        hidden_dim=cfg.model.hidden_dim,
        num_classes=cora.num_classes,
        dropout_rate=cfg.model.dropout_rate,
    )
    # Init dummy params for tree structure, then overwrite with saved values
    a_hat = jnp.array(normalize_adjacency(cora.adj))
    x     = jnp.array(cora.features)
    key   = jax.random.PRNGKey(0)
    template_params = model.init({"params": key, "dropout": key}, x, a_hat, training=False)["params"]

    params = load_params(template_params, str(cfg.checkpoints_dir / "gcn_cora_baseline"))
    return model, params


# ─────────────────────────────────────────────────────────────────────────────
# Figure generators
# ─────────────────────────────────────────────────────────────────────────────

def fig_bar_accuracy(save_path):
    print("\n[Fig 1] Accuracy bar chart …")
    plot_accuracy_bar(
        baseline_acc=BASELINE_ACC,
        attacked_accs=ATTACKED_ACCS,
        defended_accs=DEFENDED_ACCS,
        dataset_name="Cora",
        save_path=save_path,
    )


def fig_bar_f1(save_path):
    print("\n[Fig 2] F1 bar chart …")
    metrics_table = {
        "baseline": {k: {"f1": BASELINE_F1} for k in ATTACKED_ACCS},
        "attacked":  {k: {"f1": v} for k, v in ATTACKED_F1.items()},
        "defended":  {k: {"f1": v} for k, v in DEFENDED_F1.items()},
    }
    plot_metrics_grouped(
        metrics_table=metrics_table,
        metric="f1",
        dataset_name="Cora",
        save_path=save_path,
    )


def fig_line_attack_defense(save_path):
    print("\n[Fig 3] Attack-defense trajectory line plot …")
    plot_attack_defense_line(
        baseline_acc=BASELINE_ACC,
        attacked_accs=ATTACKED_ACCS,
        defended_accs=DEFENDED_ACCS,
        dataset_name="Cora",
        save_path=save_path,
    )


def fig_graph_comparison(cora, model, params, save_path):
    """Graph structure comparison for two representative attacks."""
    print("\n[Fig 4] Graph comparison (Nettack) …")

    attacked_path = ROOT / "results" / "attacked_graphs" / "cora_nettack.npz"
    defended_path = ROOT / "results" / "defended_graphs" / "defended_nettack.npz"

    if not attacked_path.exists() or not defended_path.exists():
        print("  [Skip] attacked/defended graphs not found")
        return

    g_attacked = load_graph_npz(attacked_path, cora)
    g_defended = load_graph_npz(defended_path, cora)

    # Use test nodes near the graph center as "center_nodes"
    test_nodes = np.where(cora.test_mask)[0][:5].tolist()

    plot_graph_comparison(
        adj_clean=cora.adj,
        adj_attacked=g_attacked.adj,
        adj_defended=g_defended.adj,
        labels=cora.labels,
        center_nodes=test_nodes,
        attack_name="nettack",
        dataset_name="Cora",
        hops=2,
        save_path=save_path,
    )

    print("\n[Fig 4b] Graph comparison (Feature Perturbation) …")
    attacked_path_fp = ROOT / "results" / "attacked_graphs" / "cora_feature_perturbation.npz"
    defended_path_fp = ROOT / "results" / "defended_graphs" / "defended_feature_perturbation.npz"
    if attacked_path_fp.exists() and defended_path_fp.exists():
        g_atk_fp = load_graph_npz(attacked_path_fp, cora)
        g_def_fp = load_graph_npz(defended_path_fp, cora)
        plot_graph_comparison(
            adj_clean=cora.adj,
            adj_attacked=g_atk_fp.adj,
            adj_defended=g_def_fp.adj,
            labels=cora.labels,
            center_nodes=test_nodes,
            attack_name="feature_perturbation",
            dataset_name="Cora",
            hops=2,
            save_path=save_path,
        )


def fig_degree_distributions(cora, save_path):
    print("\n[Fig 5] Degree distributions …")
    for attack_name in ["nettack", "feature_perturbation", "gradient_attack"]:
        atk_path = ROOT / "results" / "attacked_graphs" / f"cora_{attack_name}.npz"
        def_path = ROOT / "results" / "defended_graphs" / f"defended_{attack_name}.npz"
        if not atk_path.exists():
            continue
        g_atk = load_graph_npz(atk_path, cora)
        g_def = load_graph_npz(def_path, cora) if def_path.exists() else g_atk
        plot_degree_distribution(
            adj_clean=cora.adj,
            adj_attacked=g_atk.adj,
            adj_defended=g_def.adj,
            attack_name=attack_name,
            dataset_name="Cora",
            save_path=save_path,
        )


def fig_embeddings(cora, model, params, save_path):
    """t-SNE of GCN hidden embeddings for clean / attacked / defended."""
    print("\n[Fig 6] t-SNE embeddings …")

    # Clean embeddings from saved baseline params
    emb_clean, _, _ = predict(model, params, cora)
    labels_np = np.array(cora.labels)

    for attack_name in ["gradient_attack", "feature_perturbation", "nettack"]:
        atk_path = ROOT / "results" / "attacked_graphs" / f"cora_{attack_name}.npz"
        def_path = ROOT / "results" / "defended_graphs" / f"defended_{attack_name}.npz"
        if not atk_path.exists():
            continue

        g_atk = load_graph_npz(atk_path, cora)
        g_def = load_graph_npz(def_path, cora) if def_path.exists() else g_atk

        emb_atk, _, _ = predict(model, params, g_atk)
        emb_def, _, _ = predict(model, params, g_def)

        # Only use nodes with valid labels
        valid = labels_np >= 0
        plot_embeddings_comparison(
            emb_clean=np.array(emb_clean)[valid],
            emb_attacked=np.array(emb_atk)[valid],
            emb_defended=np.array(emb_def)[valid],
            labels=labels_np[valid],
            attack_name=attack_name,
            dataset_name="Cora",
            method="tsne",
            max_nodes=1500,
            save_path=save_path,
        )


def fig_training_curves(cora, model, save_path):
    """Re-run a short training to capture loss/val curves."""
    print("\n[Fig 7] Training curves (GCN on Cora) …")
    from models.train import train_model
    result = train_model(model, cora, cfg.model, seed=cfg.seed, verbose=False)
    plot_training_curves(
        train_losses=result.train_losses,
        val_accs=result.val_accs,
        model_name="GCN",
        dataset_name="Cora",
        save_path=save_path,
    )


# ─────────────────────────────────────────────────────────────────────────────
# Main
# ─────────────────────────────────────────────────────────────────────────────

def main():
    cfg.make_dirs()
    save_path = FIGURES_DIR

    print("=" * 60)
    print("PHASE 6 — Visualization Runner")
    print(f"Output dir: {save_path}")
    print("=" * 60)

    # Figures that need only the hardcoded result tables (fast)
    fig_bar_accuracy(save_path)
    fig_bar_f1(save_path)
    fig_line_attack_defense(save_path)

    # Figures that need the actual graph data / model
    cora = load_cora_graph()
    model, params = load_gcn_and_params(cora)

    fig_graph_comparison(cora, model, params, save_path)
    fig_degree_distributions(cora, save_path)
    fig_embeddings(cora, model, params, save_path)
    fig_training_curves(cora, model, save_path)

    print("\n" + "=" * 60)
    print(f"[Phase 6 Complete] All figures saved → {save_path}")
    figs = list(save_path.glob("*.png"))
    for f in sorted(figs):
        print(f"  {f.name}")
    print("=" * 60)


if __name__ == "__main__":
    main()
